### PR TITLE
Added Ubuntu fonts to the top left menu and Jetbrains to audio quiality select

### PR DESCRIPTION
**Pull request by Muxutruk2**
Made fonts more consistent

### CODE REVIEW

**Comment by Muxutruk2** [comment]
select should have JetBrains as the other quality select

**Comment by aandrew-me** [comment]
Shouldn't Jetbrains font be imported?

**Comment by Muxutruk2** [comment]
Isn't it already imported?

**Comment by aandrew-me** [comment]
My bad, resolve the merge conflicts so that I can merge

**Comment by Muxutruk2** [comment]
Done, didnt know i could do that

**Pull request merged**
