### PR TITLE
turkish language translation

### PR DESCRIPTION
**Pull request by nxjosephofficial**

### CODE REVIEW

**Comment by aandrew-me** [comment]
Thank you very much for your translations!

As github doesn't have localization support for README.md file (as far as I know) I will create a separate README_tr.md and put the contents there.

Regarding the tr.json, I am merging it. And in future you can translate here, https://crowdin.com/project/ytdownloader.

**Comment by aandrew-me** [comment]
I have created a README folder with README_tr.md in it, I request you to put your contents of README there.

I will close this pull request and I request you to make a new pull request where -
1. You will put the README translated to turkish in README_tr.md
2. tr.json will be where it is. (no changes)

**Comment by nxjosephofficial** [comment]
Thank you very much. I guess my tr.json file deleted. I'm translating again.. I put Readme_tr.md to READMES directory, im still working when it finished i'll make a pull request. Thank you again.

**Comment by aandrew-me** [comment]
Hey!

You don't have to translate again. Everything is saved when you are using git. Here are the contents

```
{
	"Click to paste video URL or ID [Ctrl + V]": "Click to paste video URL or ID [Ctrl + V]",
	"Preferences": "Preferences",
	"About": "About",
	"Download location": "Download location",
	"Current download location - ": "Current download location - ",
	"Enable transparent dark mode(only Linux, needs relaunch)": "Enable transparent dark mode(only Linux, needs relaunch)",
	"Please wait, necessary files are being downloaded": "Please wait, necessary files are being downloaded",
	"Video": "Video",
	"Audio": "Audio",
	"Title ": "Title ",
	"Select Format ": "Select Format ",
	"Download": "Download",
	"Select Download Location": "Select Download Location",
	"More options": "More options",
	"Start": "Start",
	"Select Language (Requires relaunch)": "Select Language (Requires relaunch)",
	"Download particular time-range": "Download particular time-range",
	"End": "End",
	"If kept empty, it will start from the beginning": "If kept empty, it will start from the beginning",
	"If kept empty, it will be downloaded to the end": "If kept empty, it will be downloaded to the end",
	"Homepage": "Homepage",
	"ytDownloader lets you download videos (and sometimes audios) from hundreds of sites like Youtube, Facebook, Instagram, Tiktok, Twitter and so on": "ytDownloader lets you download videos (and sometimes audios) from hundreds of sites like Youtube, Facebook, Instagram, Tiktok, Twitter and so on",
	"It's a Free and Open Source app built on top of Node.js and Electron. yt-dlp has been used for downloading": "It's a Free and Open Source app built on top of Node.js and Electron. yt-dlp has been used for downloading",
	"Source Code is available ": "Source Code is available ",
	"here": "here",
	"Processing": "Processing",
	"Some error has occured. Check your network and use correct URL": "Some error has occured. Check your network and use correct URL",
	"Failed to download necessary files. Please check your network and try again": "Failed to download necessary files. Please check your network and try again",
	"Try again": "Try again",
	"Unknown size": "Unknown size",
	"MB": "MB",
	"Unknown quality": "Unknown quality",
	"Downloading...": "Downloading...",
	"Some error has occured. Hover to see details": "Some error has occured. Hover to see details",
	"File saved successfully": "File saved successfully",
	"File saved. Click to Open": "File saved. Click to Open",
	"Preparing...": "Preparing...",
	"Progress": "Progress",
	"Speed": "Speed",
	"Quality": "Quality",
	"Restart app": "Restart app",
	"Subtitles": "Subtitles",
	"Download subtitles if available": "Download subtitles if available",
	"Download auto generated subtitles": "Download auto generated subtitles",
	"Extract Audio from Video": "Extract Audio from Video",
	"Extract": "Extract",
	"Downloading necessary files": "Downloading necessary files",
	"low": "low",
	"medium": "medium",
	"ytDownloader lets you download videos and audios from hundreds of sites like Youtube, Facebook, Instagram, Tiktok, Twitter and so on": "ytDownloader lets you download videos and audios from hundreds of sites like Youtube, Facebook, Instagram, Tiktok, Twitter and so on"
}
```

**Comment by aandrew-me** [comment]
You seriously deleted!? Check your old commits

**Comment by nxjosephofficial** [comment]
I was trying to sync my fork, I can't see my commits.. Unlucky but it's almost done.

**Pull request closed without merging**
