### PR TITLE
Fonts are now fully consistent

### PR DESCRIPTION
**Pull request by Muxutruk2**

### CODE REVIEW

**Comment by aandrew-me** [comment]
I dont like the fact that so many new dependencies have been added. I will check its impact

**Comment by Muxutruk2** [comment]
I really dont know why the dependecies appeared
I dont know how to work with nodejs

**Comment by aandrew-me** [comment]
You can remove the changes in package.json and packake-lock.json

**Comment by Muxutruk2** [comment]
I fixed it

**Pull request merged**
