### PR TITLE
Replaced all Arial fonts with Ubuntu and made both buttons bold

### PR DESCRIPTION
**Pull request by Muxutruk2**
It would look something like this

image

### CODE REVIEW

**Comment by Muxutruk2** [comment]
What do you think?

**Comment by aandrew-me** [comment]
I like the font, I will load the file locally instead of downloading from google.
Regarding bold fonts, I am not so sure, but it seems good :)

**Comment by Muxutruk2** [comment]
Thanks

**Comment by Muxutruk2** [comment]
select should have JetBrains as the other quality select

**Pull request merged**
